"""add credential_link key_options

Revision ID: 1d362ec77f33
Revises: 7e2e0b6453f3
Create Date: 2026-07-18 18:49:36.446177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d362ec77f33'
down_revision: Union[str, Sequence[str], None] = '7e2e0b6453f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_options', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential_links', schema=None) as batch_op:
        batch_op.drop_column('key_options')

    # ### end Alembic commands ###
