"""initial schema

Revision ID: 2ddf7ad3d932
Revises: 
Create Date: 2026-03-28 01:43:33.896647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ddf7ad3d932'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('op_id', sa.String(length=36), nullable=False),
    sa.Column('cred_type', sa.Enum('password', 'private_key', 'public_key', name='cred_type'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('key_type', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['op_id'], ['operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hosts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('op_id', sa.String(length=36), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['op_id'], ['operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('connection_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('op_id', sa.String(length=36), nullable=False),
    sa.Column('src_host_id', sa.String(length=36), nullable=True),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('src_user', sa.String(length=255), nullable=True),
    sa.Column('dst_host_id', sa.String(length=36), nullable=True),
    sa.Column('dst_ip', sa.String(length=45), nullable=False),
    sa.Column('dst_user', sa.String(length=255), nullable=True),
    sa.Column('connection_type', sa.Enum('ssh', 'scp', 'rsync', 'sftp', 'ssh_copy_id', 'unknown', name='connection_type'), nullable=False),
    sa.Column('direction_context', sa.Enum('from_src_logs', 'from_dst_logs', name='direction_context'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_line', sa.Text(), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dst_host_id'], ['hosts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['op_id'], ['operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_host_id'], ['hosts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('host_ips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('cidr', sa.String(length=3), nullable=True),
    sa.Column('interface_name', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Enum('manual', 'parsed', name='hostip_source'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('host_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('shell', sa.String(length=255), nullable=True),
    sa.Column('home_dir', sa.String(length=512), nullable=True),
    sa.Column('source', sa.Enum('manual', 'passwd_file', 'authorized_keys', 'home_dir_found', 'log_evidence', name='hostuser_source'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credential_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('host_user_id', sa.String(length=36), nullable=True),
    sa.Column('relationship', sa.Enum('found_on_disk', 'authorized_key', 'accepted_password', 'used_in_connection', name='credlink_relationship'), nullable=False),
    sa.Column('file_source', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_user_id'], ['host_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credential_links')
    op.drop_table('host_users')
    op.drop_table('host_ips')
    op.drop_table('connection_records')
    op.drop_table('hosts')
    op.drop_table('credentials')
    op.drop_table('operations')
    # ### end Alembic commands ###
