"""add hostip addr_type and sudo_rules

Revision ID: 303416a8afdd
Revises: 49bf7a89f577
Create Date: 2026-04-21 18:04:03.139776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303416a8afdd'
down_revision: Union[str, Sequence[str], None] = '49bf7a89f577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sudo_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('op_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('subject_type', sa.Enum('user', 'group', name='sudorule_subject_type'), nullable=False),
    sa.Column('run_as', sa.String(length=255), nullable=False, server_default='root'),
    sa.Column('commands', sa.Text(), nullable=False),
    sa.Column('nopasswd', sa.Boolean(), nullable=False, server_default='0'),
    sa.Column('raw_line', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['op_id'], ['operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_op_id_created_at'))

    with op.batch_alter_table('host_ips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addr_type', sa.Enum('ipv4', 'ipv6', 'hostname', name='hostip_addr_type'), nullable=False, server_default='ipv4'))
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host_ips', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)
        batch_op.drop_column('addr_type')

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_op_id_created_at'), ['op_id', 'created_at'], unique=False)

    op.drop_table('sudo_rules')
    # ### end Alembic commands ###
