"""add ssh_config_patterns table

Revision ID: 49bf7a89f577
Revises: fea0589e10b3
Create Date: 2026-04-21 16:05:33.947404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49bf7a89f577'
down_revision: Union[str, Sequence[str], None] = 'fea0589e10b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssh_config_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('op_id', sa.String(length=36), nullable=False),
    sa.Column('source_host_id', sa.String(length=36), nullable=False),
    sa.Column('pattern', sa.String(length=512), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['op_id'], ['operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ssh_config_patterns')
    # ### end Alembic commands ###
