"""add ssh_config_pattern origin and direction

Revision ID: b69f12d97634
Revises: 1d362ec77f33
Create Date: 2026-07-18 19:04:36.700827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69f12d97634'
down_revision: Union[str, Sequence[str], None] = '1d362ec77f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssh_config_patterns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=32), server_default='ssh_config', nullable=False))
        batch_op.add_column(sa.Column('direction', sa.String(length=16), server_default='outbound', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssh_config_patterns', schema=None) as batch_op:
        batch_op.drop_column('direction')
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
