"""add host status

Revision ID: e033c52fceee
Revises: 303416a8afdd
Create Date: 2026-04-21 18:34:14.462434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e033c52fceee'
down_revision: Union[str, Sequence[str], None] = '303416a8afdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('entry_point', 'compromised', 'pivot', 'target', 'scoped_out', 'unreachable', name='host_status'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hosts', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
